# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NBzVtplgpvMQpgc3wp7hxHZl0CbkbICr
"""

import matplotlib.pyplot as plt
import pandas

from google.colab import files
uploaded=files.upload()
df = pandas.read_csv('atlantis.csv')
x = df['year']
y = df['population']

plt.plot(x,y)
plt.title("Population of Atlantis")
plt.xlabel('Year')
plt.ylabel('Population')
plt.show()